<?php
//define('ROOT', dirname(__FILE__).'/');
define('WWJW_HOST', 'http://api.wwjw.com/');
$config = array(
	'user_id' => Mage::getStoreConfig('wwjwlinks/wwjwsettings/wwjw_userid'),
	'consumer_key' => Mage::getStoreConfig('wwjwlinks/wwjwsettings/wwjw_key'),
	'consumer_secret' => Mage::getStoreConfig('wwjwlinks/wwjwsettings/wwjw_secret')
);
function curlPost($url,$data)
{
	try {
		$ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, $url);
	    curl_setopt($ch, CURLOPT_HEADER, false);
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	    curl_setopt($ch, CURLOPT_POST, true);
	    curl_setopt($ch, CURLOPT_TIMEOUT, 2);
	    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
	    $data = curl_exec($ch);
	    curl_close($ch);
	    return $data;
		
	} catch (Exception $e) {
		echo $e->getMessage();
	}

}

function sendApi()
{
	global $config;
	$config['domain'] = $_SERVER['HTTP_HOST'];
//	$file = ROOT . 'config/send.txt';
	//if (!is_file($file)) {
	if (true) {
		//file_put_contents($file, 1);
		$sendApiUri = WWJW_HOST . "request/isuse";
		$dat = http_build_query($config);
		
		$result = curlPost($sendApiUri, $dat);
		$result = json_decode($result);
		if ($result->err == 0) {
			return 1;
		} else {
			return 0;
		}
	}
}
$dirpath = str_replace('\\', '/', dirname(__FILE__));
$REQUEST_URI = $_SERVER['REQUEST_URI'];
$URIS = explode('/', $REQUEST_URI);

$position = strpos($URIS[1], '?') ? '../' : $URIS[1];
$pos = $position == '../' ? '' : $position;

$request_uri = WWJW_HOST. 'request/cate';
$request_dat = http_build_query($config).'&domain='.$_SERVER['HTTP_HOST'].'&pos='.$pos;
$result = curlPost($request_uri, $request_dat);
$result = json_decode($result);
$type = 0;
$data = array();
if ($result->err == 0) {
	$dd = sendApi();
	$data = $result->msg;
	foreach ((array)$data as $key=>$value) {
		$data[$key] = (array)$value;
	}
	$type = $result->type;
} else {
	
}
?>
<style type="text/css">
.height1{height:7px;overflow:hidden;clear:both;}
.height2{height:9px;overflow:hidden;clear:both;}
.height3{height:10px;overflow:hidden;clear:both;}
.height4{height:15px;overflow:hidden;clear:both;}
.lay{width:900px;margin-left:auto;margin-right:auto;}
table.tabs{text-align:center;}
table.tabs tr{height:26px;}
table.tabs tr td{color:#1C75E2;}
table.tabs tr.nrs td{color:#343434;}
table.tabs tr td span{color:#FF5700;}

.nr_one{border:1px solid #DDF2FF;}
.nr_one h3{background:url(../images/bg2.gif) no-repeat;height:27px;line-height:29px;overflow:hidden;font-weight:normal;font-size:14px;color:#424242;}
.nr_one h3 span{display:block;float:left;color:#fff;width:60px;font-family:Verdana, Tahoma, Arial, sans-serif;font-size:115%;text-align:center;font-weight:bold;margin-right:20px;}
.nr_one p{padding:15px;color:#424242;line-height:1.8em;}
.nr_one p tt{color:#FF9900;}

.nr_two{border:1px solid #EFF9FF;height:1%;overflow:hidden;}


.bor_1{border:1px solid #DFF2FF;background:#F9FCFF;padding:0 10px;}
.bor_1 h3{height:39px;border-bottom:1px dashed #DBECFE;background:url(../images/ico3.gif) no-repeat;padding-left:35px;color:#1C75E2;font-size:14px;font-weight:bold;line-height:41px;overflow:hidden;}
.bor_1 ul{padding:8px 5px 8px 35px;height:1%;overflow:hidden;}
.bor_1 ul li{width:900px;float:left;}

/*copyright*/
#copyright{height:93px;border-top:1px solid #D5E0EF;padding:10px 0;text-align:center;line-height:2em;color:#979797;font-size:14px;}
#copyright a{color:#3B7BD5;}
#copyright p{color:#3B7BD5;}
#copyright span{color:#1C75E2;}

.tab_11{}
.tab_11 h4{color:#F9A911;font-size:14px;font-weight:bold;height:25px;line-height:27px;overflow:hidden;}
.tab_11 ul{margin:0;padding:0;}
.tab_11 ul li{width:220px;float:left;line-height:25px;}
.tab_11 ul li a{color:#3B7BD5;font-size:14px;}

/**/
.list_11{clear:both;background:#fff;border-top:1px solid #E1EFEF;border-bottom:1px solid #E1EFEF;}
.list_11 p{height:27px;line-height:29px;overflow:hidden;padding-left:20px;padding-right:20px;}
.list_11 p span{float:right;}
.list_11 p.a1{font-size:14px;font-weight:bold;color:#0069CA;}
.list_11 p.a1 span.c1{color:#0069CA;font-size:12px;font-family:Verdana, Tahoma, Arial, sans-serif;}
.list_11 p.a1 span.c1 b{font-size:160%;}
.list_11 p.a2{color:#555;}
.yh{display:none;}
a.links_11{display:block;height:59px;overflow:hidden;padding-top:10px;}
a.links_11:hover{background:#F7FDFD;text-decoration:none;}
.h1{height:1px;overflow:hidden;background:url(../images/h1.gif) repeat-x;}
.btn_11{display:block;float:left;background:url(../images/btn1.gif) no-repeat;width:94px;height:22px;}
.btn_12{display:block;float:left;background:url(../images/btn2.gif) no-repeat;width:94px;height:22px;}

.foot{float:left; width:100%;height:auto; position:relative }
.foot_zc{float:left; width:100%;height:auto; position:relative;}
.foot_leftbg{left:0;footer:0; background:url(../images/foot_bg1.gif) no-repeat; width:251px; height:204px;  position: absolute; z-index:-1;}
.foot_rightbg{right:0;footer:0; background:url(../images/foot_bg2.gif) no-repeat; width:289px; height:204px; position:absolute; z-index:-1;}
.button {
overflow: visible;
width: auto;
border: 0;
padding: 0;
margin: 0;
cursor: pointer;
position: relative;
background: url(http://www.girlmerry.com/skin/frontend/default/se105/css/../images/sprites_repeat.gif) repeat-x 0 -300px;
height: 21px;
margin-left: 5px;
}
</style>
<div class="lay">
	<p class="height4" />
	<div id="path">Postion:<a href="<?php echo $this->getUrl('wwjw_links/index/index');?>">Link Home</a>
		<p class="height4" />
		<div id="lays_1" class="bor_1">
			<ul>
				<li>
					<div class="tab_11">
						<p class="height4" />
						<h5>
							<form action="<?php echo $this->getUrl('wwjw_links/index/post');?>" method="GET">
							Search Links:<input type="text" name="TITLE" size="40"/> <input type="submit" value="Search" />
							<a href="http://<?php if ($type == 1) echo 'www'; else echo 'd'?>.wwjw.com/submit.php" id="add-site" target="_blank">[Add your Site] </a>
							</form>
						</h5>
						<ul>
						<?php
						foreach ((array)$data as $key=>$value) {?>
						<li><a href="<?php echo $this->getUrl('wwjw_links/index/post');?>?id=<?php echo $value[ID];?>&type=<?php echo $value[TYPE];?>"><?php echo $value[TITLE];?></a></li>
						<?php } ?>
						</ul>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<div style="clear: both;">
		<div class="lay" id="copyright">
			<p><a href="/">Home</a> | <a target="_blank" href="http://e.wwjw.com">Package Tracking</a></p>
			<p>Copyright  &copy;  2004-2013 Powered by <a target="_blank" href="http://www.wwjw.com">WWJW</a></p>
		</div>
	</div>
</div>

 